Submission 1
gloveboxhq/sql-challenges pull request #1
Opened 2024-04-22 16:46 UTC by jasonephraim

@ARolek - Thanks again for the challenge.

I interpreted your instructions to mean I shouldn't change the initial tables so I did some extra work updating the carriers(id) data type to match the others

2024-04-22 23:28 UTC, ARolek requested changes
Looks great overall. I left a few questions inline that I would like your responses to.

2024-04-22 23:28 UTC, ARolek commented on reports/get_top_10_users_by_policy_count.sql
> +LEFT JOIN
Why did you opt to use a LEFT JOIN here instead of a JOIN?

2024-04-22 23:28 UTC, ARolek commented on reports/get_total_policies_count_by_carrier.sql
> +LEFT JOIN
Same question here, why did you choose to use a LEFT JOIN?

2024-04-22 23:28 UTC, ARolek commented on schema/schema.sql
> +ADD COLUMN new_id serial;
For this challenge this is fine as I wasn't specific about what parts of the data model should be kept, but using type of `text` for the `id` column was intentional. For example, the `id` could be `nationwide`, `safeco`, etc. 

Why did you choose to change the `id` type?

2024-04-22 23:28 UTC, ARolek commented on schema/schema.sql
> +RENAME TO carriers;
This was beyond the scope of the challenge, but it's great to see you write a data migration here. Demonstrates you're aware of the steps involved.

2024-04-22 23:28 UTC, ARolek commented on schema/schema.sql
> +FROM generate_series(1, 1);
Excellent.

2024-04-23 00:39 UTC, jasonephraim commented on reports/get_top_10_users_by_policy_count.sql
> +LEFT JOIN
> Why did you opt to use a LEFT JOIN here instead of a JOIN?

I used LEFT JOIN because I wanted to ensure I displayed users who had zero policies. If I recall correctly, JOIN defaults to an INNER JOIN, which would ignore users with 0 policies.

2024-04-23 00:40 UTC, jasonephraim commented on reports/get_total_policies_count_by_carrier.sql
> +LEFT JOIN
@ARolek same answer as first comment. I wanted to ensure carriers with no policies were taken into account.

2024-04-23 00:46 UTC, jasonephraim commented on schema/schema.sql
> +ADD COLUMN new_id serial;
@ARolek Ahh I see. I chose to change it to the `id` type because the other two tables followed that format and I assumed the `full_name` column took care of the actual carrier name similar to `name` and `type_id` on the `users` and `policies` tables, respectively.

I started working on that conversion before I got deep into the challenge, figuring if I had to add a reference or something it was better to keep all IDs the same type.

2024-05-22 19:35 UTC, closed without merging